package provider

import (
	"context"
	"fmt"

	"github.com/coreplanelabs/terraform-provider-polylane/internal/client"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type gcpConnectionRequestResource struct{ client *client.Client }
type gcpConnectionRequestResourceModel struct {
	WorkspaceID    types.String `tfsdk:"workspace_id"`
	ProjectID      types.String `tfsdk:"project_id"`
	IdempotencyKey types.String `tfsdk:"idempotency_key"`
	ID             types.String `tfsdk:"id"`
	Subject        types.String `tfsdk:"subject"`
	IssuerURL      types.String `tfsdk:"issuer_url"`
	PushEndpoint   types.String `tfsdk:"push_endpoint"`
	ResourcePrefix types.String `tfsdk:"resource_prefix"`
	Status         types.String `tfsdk:"status"`
	ExpiresAt      types.String `tfsdk:"expires_at"`
}

var _ resource.ResourceWithConfigure = &gcpConnectionRequestResource{}

func NewGCPConnectionRequestResource() resource.Resource { return &gcpConnectionRequestResource{} }
func (r *gcpConnectionRequestResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gcp_connection_request"
}
func (r *gcpConnectionRequestResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{Description: "Creates a beta Google Cloud connection request. Use the returned public identity to provision Google resources before activation.", Attributes: map[string]schema.Attribute{
		"workspace_id":    schema.StringAttribute{Required: true, Description: "Polylane workspace ID.", Validators: []validator.String{stringvalidator.RegexMatches(workspaceIDPattern, "must be a valid workspace_id")}, PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		"project_id":      schema.StringAttribute{Required: true, Description: "Google Cloud project ID.", Validators: []validator.String{stringvalidator.RegexMatches(gcpProjectIDPattern, "must be a valid project_id")}, PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		"idempotency_key": schema.StringAttribute{Optional: true, Computed: true, Description: "Optional unique creation key. A fresh UUID is generated by default. Explicit keys cannot be reused after revocation or expiration.", Validators: []validator.String{stringvalidator.LengthBetween(1, 128)}, PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		"id":              schema.StringAttribute{Computed: true, Description: "Immutable Polylane request ID.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		"subject":         schema.StringAttribute{Computed: true, Description: "Immutable federation subject.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		"issuer_url":      schema.StringAttribute{Computed: true, Description: "Public OIDC issuer URL.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		"push_endpoint":   schema.StringAttribute{Computed: true, Description: "Authenticated Pub/Sub delivery endpoint and audience.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		"resource_prefix": schema.StringAttribute{Computed: true, Description: "Google resource name prefix issued by Polylane.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		"status":          schema.StringAttribute{Computed: true, Description: "Request lifecycle status."},
		"expires_at":      schema.StringAttribute{Computed: true, Description: "Pending request expiration timestamp."},
	}}
}
func (r *gcpConnectionRequestResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	apiClient, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data Type", fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData))
		return
	}
	r.client = apiClient
}
func (r *gcpConnectionRequestResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Unconfigured Polylane Client", "Configure the Polylane provider before managing connections.")
		return
	}
	var plan gcpConnectionRequestResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if plan.IdempotencyKey.IsUnknown() || plan.IdempotencyKey.IsNull() {
		plan.IdempotencyKey = types.StringValue(uuid.NewString())
	}
	remote, err := r.client.CreateGCPConnectionRequest(ctx, client.CreateGCPConnectionRequestInput{WorkspaceID: plan.WorkspaceID.ValueString(), ProjectID: plan.ProjectID.ValueString(), IdempotencyKey: plan.IdempotencyKey.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to Create GCP Connection", err.Error())
		return
	}
	if remote.Status != "pending" && remote.Status != "active" {
		resp.Diagnostics.AddError("GCP Request Is No Longer Usable", "The idempotency key refers to a revoked or expired request. Use a fresh idempotency_key to reconnect.")
		return
	}
	setGCPConnectionRequestState(&plan, remote)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gcpConnectionRequestResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Unconfigured Polylane Client", "Configure the Polylane provider before managing connections.")
		return
	}
	var state gcpConnectionRequestResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	remote, err := r.client.GetGCPConnectionRequest(ctx, state.WorkspaceID.ValueString(), state.ID.ValueString())
	if client.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Unable to Read GCP Connection", err.Error())
		return
	}
	if remote.Status == "revoked" || remote.Status == "expired" {
		resp.State.RemoveResource(ctx)
		return
	}
	setGCPConnectionRequestState(&state, remote)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *gcpConnectionRequestResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var state gcpConnectionRequestResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *gcpConnectionRequestResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Unconfigured Polylane Client", "Configure the Polylane provider before managing connections.")
		return
	}
	var state gcpConnectionRequestResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteGCPConnectionRequest(ctx, state.WorkspaceID.ValueString(), state.ID.ValueString()); err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Unable to Delete GCP Connection", err.Error())
	}
}
func setGCPConnectionRequestState(state *gcpConnectionRequestResourceModel, remote *client.GCPConnectionRequest) {
	state.WorkspaceID = types.StringValue(remote.WorkspaceID)
	state.ProjectID = types.StringValue(remote.ProjectID)
	state.ID = types.StringValue(remote.ID)
	state.Subject = types.StringValue(remote.Subject)
	state.IssuerURL = types.StringValue(remote.IssuerURL)
	state.PushEndpoint = types.StringValue(remote.PushEndpoint)
	state.ResourcePrefix = types.StringValue(remote.ResourcePrefix)
	state.Status = types.StringValue(remote.Status)
	state.ExpiresAt = types.StringValue(remote.ExpiresAt)
}
